spring.application.name=MediBook

#Configuraciones de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuraciones de JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.security.jwt.token.signature=${JWT_SIGNATURE}
spring.mail.frontend.url=http://localhost:5173/reset-password
spring.security.user.role=${PUBLIC_ROLE}
spring.security.user.doctor.role=${DOCTOR_ROLE}

#configuraciones de email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nickopruebas@gmail.com
spring.mail.password=uwhe kzeh nwwe bwbs
spring.mail.test-connection=true
#indico que voy a usar el protocolo smpt para enviar correos
spring.mail.protocol=smtp
#Indico a javamail que para conectarse al servidor debe recibir el usuario y contrasena
spring.mail.properties.mail.smtp.auth=true
#activo un cifrado de seguridad para conexion segura
spring.mail.properties.mail.smtp.starttls.enable=true
